const GET_GAIA_EXERCISE_API = 'GET_GAIA_EXERCISE_API';
const GET_GAIA_EXERCISE_SUCCESS = 'GET_GAIA_EXERCISE_SUCCESS';
const GET_GAIA_EXERCISE_FAILURE = 'GET_GAIA_EXERCISE_FAILURE';

export {
    GET_GAIA_EXERCISE_API,
    GET_GAIA_EXERCISE_SUCCESS,
    GET_GAIA_EXERCISE_FAILURE
}